server:
  port: 33400

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: midas-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.jpmc.midascore.foundation.Transaction

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  h2:
    console:
      enabled: true

general:
  kafka-topic: trader-updates