general:
  kafka-topic: trader-updates

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: midas
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.jpmc.midascore.foundation.Transaction
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 33400